title:              Deep Shekhar Singh
email:              24318@iiitu.ac.in
description:        Student at IIIT Una || Exploring Android Dev 
author:             Deep Shekhar Singh
baseurl:            ""
url:                "https://deepssingh.me"

# Social Profiles
github_username:    DSingh0304  
linkedin_username: deepshekharsingh

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
